#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Tejeswini Sundaram
tagline: Project Assitant @HPC LAB, SERC, IISc. # author name
keywords: "Tejeswini Sundaram stejeswini tejeswinisundaram tejeswini iisc serc hpc" # html meta keywords
name: Tejeswini Sundaram
# Short bio or description (displayed in the header)
description:  

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/9999955?v=3&s=460

aboutme: Hi, this is Tejeswini S.  # these are shown on aboutme-box(sidebar).
aboutme_photo: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQSERQSEhQUEhQWFhQWFRUXFRUVFRUUFBcWFxUUFBQYHCggGBolHBQVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQFywkHBwsLCwsLCwsLCwsLCwsLCwsLCwsLCwrLCwsLCwsLCwsLCwsNywrLCw3LCs3LCsrKywrK//AABEIAOEA4QMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAwQFBgcBAgj/xAA9EAABAwIDBQYEAwcDBQAAAAABAAIRAwQFITEGEkFRYQcTInGBkTKhwdEUQrEjM1Jy4fDxNGKCFlNjc7L/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAAjEQEBAAICAgICAwEAAAAAAAAAAQIRAyESMTJBEyIzUWEE/9oADAMBAAIRAxEAPwDa0IQsg6hCEAIQuIDq8lyTq1oTOtXWeXJIDt9wAkfxSgMVxunRaS97RHAkT6Dis/xjtOBaW0mlpn4jy6LH8mWXoNgF2EuKoXz1b9olw2RO8JynUKdwztNdvDvR4eMK98k9wNqDwuys/pdoVtA8RHmFPWG0lKqJa9pHmnOX+4FgC9hNKFyHCQU7aVpMpQ9LiEKgEIQgBCEJgIQhMghCEAIQhACEIQHF1cXVJhCFxACbXFeMgvVzWgKIxG+bRpuqVCGtaJJKw5M9dQPV7eNptL6jg1o1JMBZltV2nCSy18XAvOnoqZtltbUvapgkUQfAzgRzPOVDUaJqGYDRPAZeyWHDvvI3q+xCpXeXPc5xJnVNXMdOhUu60ayCXHyAzTqvUa78oAj80SfQLo1J6LaEt7UuKcfgHeysNlatLZy6nL6qSs8KY+DvT6ZKMs5DktUxls/inLC+mAQ8j1IV1vMBEN3fI9VDX+AOiYMRkpnJjVXjruD9oNzQc0OdvtGUGNPNbNsztNSu6Qew5/mbxBWDPwJwGh+qebPXlSzqCox0R8TToR90anvErNPo6nUle1W8Axttek17MwQrBSqSFeOW0lEIQrAQhCCCEITAQhCAEIQgBCEIDi6hCkwvFR0Bekyu6vBRnlqA3r1NXEwFhfaLta67qmhSMUWGMvzuHE9FeO1Hab8PQ7imf2tUZkflbxPmVim+Qeqy4sfK7pwuy3MwrDhVu1pH5nfIfdQNrJgTHXlzKnLSi8/u9GwN6F0pySb7OnT8T3B7zMD+HmY5qJvt0SYiTkpKnhm4DVrkl2rW6kk6TyUJiLHOcSf8dEFCVO9gzA6cvZSFHHKhcAHQBn/VQlSjunNTGzODuuHzo0RP2WWcmu22C4YHXdud48kycuJPVS7GOcCYI806wzCd0DkNApQUeC8/L27J0r4w+RnrChcZwXwkgZ81fHUE1uLfJGPJcaMsJkoWyWN1LFxa+XUXaj+E8XLZMIvW1aYewy0rJto7IsO+1u8w5PA18wlezXaA03uob3hklu9y5LsxylnlHDnhca2hj5XtNLWrvZp2t5doCEIVgIQhBhCEIAQhCCCEIQAhCFJvFV0BQeKXzaNN9RxgNBPspi8PhWY9rmJd3aimNahj04rn5d2yBkuO4o65uKlVxJkmOg4AKOOZyXJhdY9dGMkmjSdHdlrBkB8TuJ5q7Yc5lNjIHxHLn0n0VCpv3IOp1KnrGqXuaHmJ9g1VpNWW6tQ8kgEtAkkfmedBKj6uHFtNzjzn1U1VxFrKTAIAA3j6ZBRdfF+9pEAQOuphSlU7pm8d7mtI7PbAfhweJJJ91R61HeDev6BaRsU9oBpt0aGz5nVZcs3i34rqrSyhkuGkn+6ISDwuOx0ymxYmtZqePSZprOxpENfWm80hUPHNn6lJ3f0ASQZc0a+YWptoqnbYY25jxb2zQ+q7I8YnRacW5emfJqxaNgMa7+g0k5xBB1kGD6q6grIdnbOvZubvua4PdLgPyuOvmDC1PDrkPYCF2ceUvTissO0IQtiCELqZuIXUIDiEIQAhCEAIXF1SCF5osR7bK572izk0u+cLb7v4Vh3bUyK1F3Njh81jl/JAzGUrTMBINSj10GcWvicJ5qaGb2t55noAomxMTwgH5qTtKkuLx4YEc9BmUFYdbRX8kMaciBPoIA+vqlrI7xY3gBChWDvKjnDPj9JVhsQA7QDdbIlTS0kLxrd0OBGUSPIxqrnsHagUu8/jzPKJgQqNhOCVLkxO7TLvEeYGsLWLGkKYDBoAAIyyAgLDlz10248ftJsXHU0NqABR19tLQpZFxcf9on3Oiw15Nd6P+6Xh9OFDHaxp+FkgmJ3hr5DRS1rdd4BlCVxVMjDFrvu2EjWFULWo2k91w8Avdk0cRPLqVb8cpENOUngqFiNZpdUJL21aTmdy0NOZB8VSVXHjvYyOr7F67HNdVoPYwnJzhHsrxgOIgHP4XwR0Vcx/FHXVGlT3TI3XVHkQN4DRo9Sl7NrgxoHDRVvHHLpjnjle60cFCjsFut+mJ1GRUiuvG7jELqEKgEIQgguLqEBxC6hBvKEIUglcDwlYz210PDQf1cFtL9FlnbJZ71oHfwPn0ORWOfWcoYcV7nivLgusaujZnFB+vUJ06rFLI8wUza+SJ4CPZenmRHVAOsPrGRAJ8lPU64L93Scv8qMwO7FIP0kt119F22vZrh8DWSCJHsook3Wu7P0mspsDR+QH3zUy+vuNLjyVcwauCwFpyPPL26KSpO76r3c+FsF32XBb5ZOzWod2tlUuhvPcadLkMi5erjCrakM2Bx5uzKe4hijaLMyAAPYKo07k3dxRk1GUKhc0PEAudwAHALWft1iz8dd1J0alAO8LGA+Sm7StlIUHj2DW9EtbSfU7z+EO3/V0/CpfDZNJu9qFGU8b7azVm9HtQh4gqFxGz8YeQHEDdBgSG8v6qWpthKbs5FZ+VHjFepWu8eilaVlklXW+4ZGnJPaQBCUh2kMMd3biOBVgaVXbzLPkpu0fLQuzgy305OXHVOULgXV0RkEIQmAhCEAIQhAeV1CFJuQqjt/h/eWlZo4sPyE/RW5NMTtw+m5pEyCPdZ5zcD5IqMgkcl2nkcxOR+YU9tpgxtblzY8JJc09DwVeK0xu4orTXuuYIHT9UmHaJxeu8XMQP0VUEwQnWDu/bMHUJhHzTuzpkODhwII9FF9HPbYsPogAN0iI8uqnrKgKe87OXGSeaqeB3vfBj/RzeRVwt2lwg6Bed99u6+ld2ktn3D202jep574ktJ5Z8k7wfZttKm3vHuLmmWeKN0mPhA00U/SseMQnIs51WkzsmmdQjLUF0+54lTVBoAgJVtgAvcbqz7VbCTjGSUotSYdDiXeich5f8MAddVWOOypWpTG6ogXG44hOatctBGqgbitElxzKWd7LGJK8ryFMYPVlo8gq9h432En0UvhtQgM5fCfofmteC6rLnTwXV5Ycl6XbHMEIQmAhCEAIQhAcQhCgwuELq4gMm7ZMG3qHfNEljs+jXa/RYm4L6k2ptRUoVmOEhzHD5L5erCCRyWfFe7DhPeStR8wn2A4HVu37lJsxqToFbT2Y1t2e8YDEwZz6SNFplnJ7aTC2bUVkaHVaHsrhVJ9EB4BJHsqtV2Ruqbs6c9QQQrNgNM0SGnXKVjy5y49Vphx3faZw3DTRreA+AnPy4wr5YkQI04KvXjgKYeMiNPVO9l7vvKU6w5zR5A5Lmt3NtZLta2RCdUWSmFJyd0qqeNm+0ZSnNSnko6o2XgJ5UrZJjbul7iqzst6LHchy5glD6gaCdAkL27awSSor8Q6oZIygwOAnj5pxWOFouLzMhoz5lRVa0Jlx1OpU4yiG9PPVNrmpveFo9VOWMjfGEMIdDSFL4WfCRzMKIpM3ZCk8LPhI470hHF7cnMnrZ2SWTe3TgLuxrndQhCoBCEIAXEIQAhCFICELjkBF41T3mlvNpHuvl3FLEsuKlKM2vc2PIr6pvhxWDX9QUcUuKrmtO69xAdp4tCAscLrOnFu7LsLFO0BLd17nu3pEHWB8oV9p5AgALLtntuR+J3apApvjxfwu4E9FprKnimcnDI8JOi5+Tcy268LvFEX2GDcc8c4HmqVjFmW+MZEarUWsD2bmmeay7tRqvpPpU6ThDmu3oI0ED6qPG3KWNsc/qvF7iwfTbTaZcYy5KybMUe6phvUn1OaoezODPB36sxwj7q4UrwF7GM4HP2RyTx6gx7XWi7JLsKbWLpaE9DFMZ5Um8lNiXDIap8vDmynotoepYOe4Oe7eg5DQJ9SsyeIA6JyaK8imeavej8r9OXtJpjX31801FInTIKSp0Z1RVpAaIy3eymX0ia9tGaUw92rTxzBTquRuqLw26Dqj2DPdgep1+iOP2z5vSyWj+B1CehRlI+MeUFSTV24VzPSEIWgCEIQHEIQgBCEKQF5cV6K8PMJUGeIOAbJWBdplLdud8ZB4993L7Lb8Sq7zt3gBKxTtUuWuums/gZn5uMrnxu+Q4plKqQtB2F257qLa6M0yfA/iyeB6LOg1enNOhW2eEyjTHLxr6Tq1g8NLCHTGYPxBRe1mAsuaQIEObmOccQsh2a2sr2ZaC4vpA5tJmB/tPBajhG21pWYanebu4W7wfII3pj9Fx58eWNdOOe/SJvO7tjTpbxJ3AJI1eJkfom2FXgfWc0AS06jX3Ud2j4/b16tNtM5bu8Ht0mSPoUhsbXa1zhvS5xzJ+Sdwtx2qWTpqWH18gpalWVatqqeMvFlOhZtOOck5Uc28SrLpPafE6NaEqysCmLqwKRfVA4o2PFM/iAExvsTawEuICgr7FQ3IGT0WbbS4rVrOewEtaMjHHPmrxlzuismPaybS7ftbNOh4naF3Bv3Kddl1x3nelxlxfJPHMLJS2CtE7K68VgMvEDPpmPqun8cxjmzyuTWh8UhSNB0hNWU8j/eiVt6mcc1WPTI6QhC2MIQhAcQhCAEIQoATa5cl3FML6rAKjkuoFf2gxJtBpcTnun3Xzzjl66tXfUcZLjK1btAvSabicgNOp5D6rIa5kys+CfaoUtj1Ti5oO+I5jmmVEcE8t7rdBa7MHX6QukjFz+B/ylaVUtzGjhBHA+YTt1m14mnLoEumARmke7gZqVeRnVJJBJ8ug4AKXwq5czdLuJyPHLiosslK0AZhFks0cyrXcIviaecuiII5dVKUK5Ko+xt/BNMnLUfZaJZ2w1HFefyY6y07MLuOd4vO+46KTbapenaKdHtFMpVCipZkjxEqeZbrxXoosT5KjeUYLRzKo20FOLgtHEH+i0fF6UFp5FZ7tZ4blpMwRlHPNaf89/ZPLP1VqtbkHPgpbZTFe5rNcDEGEzvX5HiVGW1Ug+Wa7bNxyPp7B7wVKYeOKcup5ghUjYipUZT3ZlkBzTrkQr4x0wVGPaCtN0heklSGvmlQtoYQuriYCESuIAXCV1eXFQCdR2Sh8RrZE+33UjdP4KtY7Xn9m3lJXNy3YZht9eb7ugEDl1PuqC8yrptmMx0yHPLWVTK3ktuKaxMmOYSgYQJI1XmOKJnotQ6x5boYBS7rrf8Ai15pnPPRdbUg5I0Zw6lBXBMrrKsjM5rtT5JBYdn3gQ6RkdOOa1vA6rXtGsZQDwWB0rgseHA8QVr+xeMd8ASOGfXquTnx126uK7ml/pjJLMaEhRMhLByyFezkkH5r2XSvDkrdiIPGGSQOqzvtDow+l/fJabeU5IWedpbPFT6T9EcXWas/jVHxF8eFvSTzlRzXQU7uZjXPU+XNMAc16DjbN2dXY7uJnc08ua061dkIzHNYn2dXO6MzxjzC17A6vhLOWn8p0WWPyQl2r0vIC9LcwhCCmHELzvhCnyh6eikahShKbXD4U5XUIzu6sEhVu6rQHPdqTp04BS95UkungqTjl/LX7v5RHqZAAXLe6FA2grF9Rw5OMdeZVdLfbj9lM3bpc88sh1UPVMSF04ejhKoV1p18l5cuALQPL14alA2V53Uzd8k9pDfbHFMglaT46ZzKkBrVY9jsWFCu2Z3Dk7mOoUJTfMg+c/ddfTLYMaqcpMppeGeq+jcOuGuAc3MEZeaePeso2I2qLRuOzGWR4cJBWk0LwOAOR8iuDOePTpnfZ7Tcvabtel2FRBYQrU1m3aSyS0kxEj3B+y1F4WW9pDS58DgCY9Qr4/nBfjWa1Xlx+XoEi4KS/D+DqJHqUzqNAXoSuOpfAcQNMgTGf9Fs2yOKBwAdG83I+XCVg9i8b2fErS9nsQblvZP3QJHEj6LLOau01slJ0he1BYLiUhod+bQ8PJTgK1wy2HpeKmh4Zar0kr2pu03O5An5KrehFU77/wAjvmhQcnmurm3GmmjPKY3lWB806e7moDELmZ5fRHLl0zQ+MXsMJ5n/AAqbjlwAwxmfrH9VN4zVfVeylTG8XEwOQHE9FYME2Sp0/wBpWAfU6iWt8gp48Le6NsetcOq1BDKbnAGSd3n1R/0bdPBeKYaN4gAuAJ1nL0W/VLZu45oAzB0yUTQwyCANIcf+Q4zzgrp9Ft863Nk9k7zSIyKbhbHtNsuO9cd1pDgOklx+I8iFleK4a6hVdTeIIP8AhVKqUxcENalqbMuHknlC0Dhl7I2EcWaI3fRPHWxB0idEr+BMZ5GAQOYPJIbM6VYfDMTl09U5D5bBgxHH9Oia3TYyiBM+sc+S9DQObpoRyKNGeWFc0ajXD+wto2cxVtWm0EhxjwnQuHLzCxIZ6BT+zWNOouA1aTxWHNhubjbjz+q2jIaaJelUVWs8Y3gNRJ8wOYlTNK5mCuC1066TrVmXaQ2H5ZZHPyWi0K+Spe3Fj3gc7ju5eXNXMtWUscfcZbVuAfCBG7n1J4kqMrnxSnVy3cfBkcOsJlUOa9KOKzVcLoKncNxlzAwZSNDzHIqvuK9tci47JqmA7VQXBzSWEgyDmyfpK0LCNp2vhpInTl5L53sr4sdIPTz81aMCx1raoc4Ac4mOg/vmsrhZ6S3g3pOijsfxPdoOESTllwniUywir3tOYc0HTgfbknLLbcaQTIgxy/5Din45X7KVU+980Kf3mf8AaZ80LP8AD/q/yLDd/CVWbnQoQo5Uo/Zr/WVPL6lXOt8KELpw+EK+3mj8KSbw/wCX6hCFQQeP6t8j/wDRWXdpn+rH/rb9UIRicUvin9muoTNIYlw/mKQGgQhII+9+E+f0Ta20PkhCqGWbw8k7YhCinj7aJhf7hvp9FY6HwD++KELysvdejPSVpaKNx/4ff9EIR/RY+2MbRfv3/wA30ChguIXqYenFye3puq4NUIWrN6GqkbH4whCnIq3rZ7903+Vn6KcHwoQhCLQhCQf/2Q== # your personal photo.

#
# Flags below are optional
#

ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

Blogroll:
      - name: Tejeswini
        href: http://tejeswinisundaram.github.io/
        title: Personal Webpage of Tejeswini Sundaram
        
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tejeswini@hpc.serc.iisc.ernet.in
  facebook:
  flickr:
  github: tejeswinisundaram
  instagram:
  linkedin: in/tejeswinisundaram
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: stejeswini
  stackoverflow: users/2507572/tejeswini-sundaram
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io)
# Used for Sitemap.xml and your RSS feed
url: http://tejeswinisundaram.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
